name: progressprodis
description: A new Flutter project.

publish_to: "none"
version: 2.0.0+1

environment:
  sdk: ">=2.19.4 <3.0.0"

dependencies:
  animated_text_kit: ^4.2.2
  bloc: ^8.1.1
  carousel_slider: ^4.2.1
  cupertino_icons: ^1.0.2
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_modular: ^6.3.2
  flutter_svg: ^2.0.4
  get_storage: ^2.1.1
  package_info_plus: ^3.0.3
  progress_desing:
    git: https://dev.azure.com/erilaz/ProgressPro/_git/progresspro.desing
    #path: ../progress_desing

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/logos/
    - assets/icons/
    - assets/images/
