name: progressprodis
description: A new Flutter project.

publish_to: "none"
version: 1.2.0+1

environment:
  sdk: '>=2.19.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  uuid: 3.0.7
  intl: ^0.18.1
  bloc: ^8.1.2
  dartz: ^0.10.1
  equatable: ^2.0.5
  get_storage: ^2.1.1
  flutter_svg: ^2.0.7
  fluttertoast: ^8.2.2
  flutter_bloc: ^8.1.3
  package_info_plus: ^4.1.0
  percent_indicator: ^4.2.3
  flutter_modular: ^6.3.2
  animated_text_kit: ^4.2.2
  carousel_slider: ^4.2.1
  supabase_flutter: ^1.10.21
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_lints: ^2.0.3
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/logos/
    - assets/icons/
    - assets/images/
    - assets/navigation/
