name: progressprodis
description: A new Flutter project. 

publish_to: 'none' 
version: 2.0.0+1

environment:
  sdk: '>=2.19.4 <3.0.0'
 
dependencies:
  bloc: ^8.1.1
  cupertino_icons: ^1.0.2
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_modular: ^5.0.3
  flutter_svg: ^2.0.4
  modular_bloc_bind: ^1.0.1
  package_info_plus: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter 
  flutter_lints: ^2.0.0
 
flutter:
 
  uses-material-design: true

  assets:
    - assets/logos/ 